### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by justinc1**
see https://github.com/ScaleComputing/HyperCoreAnsibleCollection/issues/327

Integ test:
- https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/10554972693 (was rebased later)
- https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/10618328306

### CODE REVIEW

**Review by shoriminimoe — APPROVED** [review]

**Comment by shoriminimoe** [comment]
I reviewed [the integration tests for this PR](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/10554972693).
- The `integ-run / ansible-test (time_server)` test failed for all  clusters due to a 400 error:

      fatal: [testhost]: FAILED! => {"changed": false, "msg": "Unexpected response - 400 b'{\"error\":\"10.5.11.5 is not a valid NTP server\"}'"}

  This appears to be a test setup problem. Maybe the target NTP server is having problems?

- The `integ-run / ansible-test (inventory)` test failed for all clusters due to this assertion error:

      fatal: [localhost]: FAILED! => {
        "assertion": "{{ 'ci-inventory-vm0' in hostvars }}",
        "changed": false,
        "evaluated_to": false,
        "msg": "Assertion failed"
      }

  That appears to be a feature problem. Has the inventory feature been fully implemented?

- The `integ-run / ansible-test (git_issue_41)` test failed for all clusters due to what appears to be a templating issue:

      Warning: : conditional statements should not include jinja2 templating
      delimiters such as {{ }} or {% %}. Found: "{{
      vm_created.record.0.disks.2.iso_name }}" == "cloud-init-{{
      (vm_created.record.0.uuid | split("-")) [0] }}.iso"
      fatal: [testhost]: FAILED! => {"msg": "The conditional check '\"{{ vm_created.record.0.disks.2.iso_name }}\" == \"cloud-init-{{ (vm_created.record.0.uuid | split(\"-\")) [0] }}.iso\"' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."}

- The `integ-seq-run / ansible-test (utils_login)` failed for all clusters due to an auth failure:

      TASK [utils_login : Get HC3 ping - OIDC user, from environ] ********************
      fatal: [testhost]: FAILED! => {"changed": false, "msg": "Failed to authenticate with the instance: 401 Unauthorized"}

  This looks like a bug to me. Could be in either the collection or HyperCore itself. It could also be a test problem with the OIDC server and/or the test environment.

- I'm not sure what is causing the failure for OIDC config on 10.5.11.201. The run looks like it recovered after retries, but ultimately resulted in a failure.
- There was a parsing error in the workflow file for the run. Despite the error, the tests still ran. I filed #329 for this.

@justinc1 can you confirm these findings?

**Comment by shoriminimoe** [comment]
@justinc1 I replaced the 9.4.0 VSNS with the new 9.4.17 VSNS in da6c864. That commit is built on top of this PR. I believe it captures all of the places that need it. I also have an integration test for that version: https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/10582507411.

Do you want to cherry-pick it here or should we submit it in a separate PR?

**Comment by justinc1** [comment]
> 10.5.11.5 is not a valid NTP server
This was IP of github CI runner VM; we reuse it also to run Ci NTP server. The runner had problems, during debugging I rebooted it, and it got new DHCP IP. The problem runner had - it was running out of disk "space" (but actually all inodes were used, not space). For now, I will just change the runner VM to static IP address 10.5.11.5. Maybe I need to ask Alex to reserve this (or some other IP).

> integ-run / ansible-test (inventory)

**Comment by shoriminimoe** [comment]
> During OIDC reconfiguration HC3 API (frequently) returns 500 error

I will make sure we have a tracking item for this internally. The API should be behaving that poorly.

---

I created #330 to merge the CI changes. Unless it needs changes, feel free to merge it if I'm offline.

**Pull request merged**
