### PR TITLE
ci: add publish-docs job to release workflow

### PR DESCRIPTION
**Pull request by shoriminimoe**

### CODE REVIEW

**Comment by justinc1** [comment]
Nice and ty.

I suggest we also stop building/deploying docs for gh-pages branch. We do not need this extra branch at all, so I already removed it.

**Comment by shoriminimoe** [comment]
> Nice and ty.
> 
> I suggest we also stop building/deploying docs for gh-pages branch. We do not need this extra branch at all, so I already removed it.

Sounds good to me. I will remove that trigger from the workflow file. Are there any other uses of the `gh-pages` branch in the repo that also need to be updated?

**Comment by justinc1** [comment]
gh-pages branch was created with idea to:
1. build docs from main branch, than
2. commit built docs into gh-pages branch, then
3. deploy gh-pages branch as gh-pages.

But the 2nd step is not needed at all, we can deploy directly from main branch or git tag.

**Comment by shoriminimoe** [comment]
@justinc1 I rebased this onto the latest `main` commit. Is there anything else needed for it?

**Review by justinc1 — APPROVED** [review]
Thank you. Nothing else is needed.

**Pull request merged**
